spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WebProjectDB?useSSL=false&serverTimezone=UTC
    username: root
    password: 1023
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 其他开发环境特定配置
